/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hummingbird;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author smbuthia
 */
public class Settings extends javax.swing.JFrame {
    
    protected static final String HIDE_RB_ACTION_COMMAND = "Hide";
    protected static final String STAY_PUT_RB_ACTION_COMMAND = "Stay";
    protected static final String EVADE_RB_ACTION_COMMAND = "Evade";
    private String PLAYER_PANEL_BEHAVIOUR;
    private final Properties props = new Properties();

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
//        try {
//            props.load(new FileInputStream("config.properties"));
//            vlcLocationLabel.setText(props.getProperty("VLCLocation"));
//
//        } catch (FileNotFoundException ex) {} catch (IOException ex) {
//            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        evadeRadioButton = new javax.swing.JRadioButton();
        hideRadioButton = new javax.swing.JRadioButton();
        noneRadioButton = new javax.swing.JRadioButton();
        behaviorLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        durationComboBox = new javax.swing.JComboBox();
        hideDurationLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        applyButton = new javax.swing.JButton();

        setResizable(false);

        buttonGroup1.add(evadeRadioButton);
        evadeRadioButton.setSelected(true);
        evadeRadioButton.setText("Evade ");
        evadeRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                evadeRadioButtonStateChanged(evt);
            }
        });
        evadeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evadeRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hideRadioButton);
        hideRadioButton.setText("Hide");
        hideRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hideRadioButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(noneRadioButton);
        noneRadioButton.setText("None");

        behaviorLabel.setText("Player Behavior");

        durationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5 seconds", "10 seconds", "20 seconds", "30 seconds" }));
        durationComboBox.setEnabled(false);

        hideDurationLabel.setText("Hide Duration");

        applyButton.setText("Apply Settings");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator1)
                    .addComponent(hideDurationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(durationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(behaviorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(evadeRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hideRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(noneRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(behaviorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evadeRadioButton)
                    .addComponent(hideRadioButton)
                    .addComponent(noneRadioButton))
                .addGap(15, 15, 15)
                .addComponent(hideDurationLabel)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void hideRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hideRadioButtonStateChanged
        if (hideRadioButton.isSelected()) {
            durationComboBox.setEnabled(true);
        } else {
            durationComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_hideRadioButtonStateChanged
    
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        if (evadeRadioButton.isSelected()) {
            PLAYER_PANEL_BEHAVIOUR = EVADE_RB_ACTION_COMMAND;
        } else if (hideRadioButton.isSelected()) {
            PLAYER_PANEL_BEHAVIOUR = HIDE_RB_ACTION_COMMAND;
        } else if (noneRadioButton.isSelected()) {
            PLAYER_PANEL_BEHAVIOUR = STAY_PUT_RB_ACTION_COMMAND;
        }
        
        try {
            props.setProperty("PanelBehaviour", PLAYER_PANEL_BEHAVIOUR);
            props.setProperty("HideDuration", (String) durationComboBox.getSelectedItem());
            props.store(new FileOutputStream("config.properties"), null);
        } catch (IOException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_applyButtonActionPerformed
    
    private void evadeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evadeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evadeRadioButtonActionPerformed
    
    private void evadeRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_evadeRadioButtonStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_evadeRadioButtonStateChanged
        /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel behaviorLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox durationComboBox;
    private javax.swing.JRadioButton evadeRadioButton;
    private javax.swing.JLabel hideDurationLabel;
    private javax.swing.JRadioButton hideRadioButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton noneRadioButton;
    // End of variables declaration//GEN-END:variables
}
